project:
  type: website
  output-dir: docs

website:
  title: "Ian Del Tredici"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - projects.qmd
      - birds.qmd
      - resume.qmd
    css: [styles.css, dark-styles.css]
      

format:
  html:
    theme:
      light: [minty, styles.css]
      dark: [superhero, dark-styles.css]
    toc: true
    page-layout: full
    include-after-body: _footer.html


